name: Deploy to Amazon EC2

on:
  push:
    branches: ['Personal_website']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Private Key file
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-16-171-30-151.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
          echo "${{secrets.PRIVATE_KEY}}" > ~/.ssh/PrivateKey.pem

      - name: Change the mode
        run: chmod 400 ~/.ssh/PrivateKey.pem

      - name: Update my repo in EC2
        run: |
          scp -i ~/.ssh/PrivateKey.pem server/* -o StrictHostKeyChecking=no ubuntu@ec2-16-171-30-151.eu-north-1.compute.amazonaws.com:~/app

      - name: npm install and restart
        run: |
          ssh -i "~/.ssh/PrivateKey.pem" -o StrictHostKeyChecking=no ubuntu@ec2-16-171-30-151.eu-north-1.compute.amazonaws.com << 'EOF'
          cd ~/app
          npm install
          pm2 restart all
          EOF
