name: Deploy to EC2 from docker image

on:
  push:
    branches:
      - main:['Personal_website']

  # pull_request:
  #   branches:
  #     - main:['Personal_website']

env:
  docker-username: ${{ secrets.DOCKER_USERNAME }}
  docker-token: ${{ secrets.DOCKER_TOKEN }}
  key: ${{ secrets.PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{  secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/video_app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{  secrets.DOCKER_TOKEN }}

      - name: Set permissions for private key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem

      - name: executing remote ssh commands using password to keep interactive terminal
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker stop video_app
            sudo docker rm video_app
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/video_app:latest
            echo "${{secrets.DB_DATABASE}}" > .env
            echo "${{secrets.DB_HOST}}" >> .env
            echo "${{secrets.DB_PASSWORD}}" >> .env
            echo "${{secrets.DB_SSL}}" >> .env
            echo "${{secrets.DB_PORT}}" >> .env
            sudo docker run -d --name video_app -p 4200:4200 --env-file .env ${{secrets.DOCKER_USERNAME}}/video_app:latest
